name: "1 - [FEAT] Build & PR to Develop"

on:
  push:
    branches: 
    - "feature/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Open PR to develop
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Open PR to develop"
          title: "Open PR to develop"
          body: "This PR was automatically opened by a GitHub Action"
          branch: ${{ github.head_ref }}
          base: "develop"
          labels: "automated pr, feature"
          draft: false