name: "1 - [FEAT] Build & PR to Develop"

on:
  push:
    branches: 
    - "feature/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Change to project directory
        run: cd staff-mack-escola-octogno-sistema-presenca

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Build: ${GITHUB_SHA}'
          commit-message: 'Build: ${GITHUB_SHA}'
          branch: 'build/${GITHUB_SHA}'
          base: 'develop'