name: "1 - [FEAT] Build & PR to Develop"

on:
  push:
    branches: 
    - "feature/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd frontend-app
          npm install

      - name: Build
        run: |
          cd frontend-app
          npm run build

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Build: ${GITHUB_SHA}"
          fi

  open-pr-to-develop:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Build: ${GITHUB_SHA}'
          commit-message: 'Build: ${GITHUB_SHA}'
          branch: 'build/${GITHUB_SHA}'
          base: 'develop'