name: "2 - [DEV] Build & Deploy"

on:
  push:
    branches: 
    - "develop"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd staff-mack-app-frontend
          npm install

      - name: Build
        run: |
          cd staff-mack-app-frontend
          npm run build

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Build: ${GITHUB_SHA}"
          fi
  

  open-pr-to-develop:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV


      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'PR from ${{ env.BRANCH_NAME }} -> main'
          commit-message: 'Commit from branch: ${{ env.BRANCH_NAME }}'
          branch: ${{ github.ref }}
          base: 'main'
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
  
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
  
      - name: Install dependencies
        run: npm ci
  
      - name: Build
        run: npm run build
  
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
          sync_args: --acl public-read --follow-symlinks --delete
          source_dir: './dist' # Substitua pelo diretório de saída do seu build
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2' # Substitua pela região do seu bucket

        
        