# This is a basic workflow to help you get started with Actions

name: "4 - [PROD] Build & Deploy"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: main
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
  # This workflow contains a single job called "build"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
  
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
  
      - name: Install dependencies
        run: |
          cd staff-mack-app-frontend
          npm install
  
      - name: Build
        run: |
          cd staff-mack-app-frontend
          npm run build
  
      - name: Deploy to S3
        run: |
          aws s3 sync staff-mack-app-frontend/dist/staff-mack-app-frontend/browser s3://staff-mack-controle-presenca --delete
        env:
          AWS_DEFAULT_REGION: sa-east-1
          AWS_REGION: sa-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

