name: Tag Release
on:
  push:
    branches:
      - main  # Apenas uma demonstração, você pode ajustar conforme necessário

jobs:
      # Sua configuração de construção e implantação aqui...

  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "github-actions@github.com"

      - name: Create and push tag
        run: |
          VERSION=$(date +'%Y%m%d-%H%M%S')  # Gera uma versão baseada na data e hora atual (exemplo)
          git tag -a v${VERSION} -m "Release ${VERSION}"
          git push origin v${VERSION}
